name = "Blist Theme"
license = "MIT"
licenselink = "https://github.com/apvarun/blist-hugo-theme/blob/master/LICENSE"
description = ""
homepage = "http://blist-theme.vercel.app/"
tags = []
features = []
min_version = "0.69.0"

[author]
  name = ""
  homepage = ""
